# Generated by Django 4.0.4 on 2022-11-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_is_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
